
FROM python:3.6
ADD . /app
WORKDIR /app
RUN pip install 'numpy==1.14.6'  'flask==0.12.2'  'marshmallow==3.0.0rc8' 'pymongo==3.8.0' 'requests==2.18.4'
EXPOSE 8000
CMD ["sudo" "apt" "install" "gunicorn"]
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app"]